auto: true
server: true
permalink: /:categories/:title
baseurl: /tunisiaelectiondata
//github: "http://github.com/mbaldassaro/tunisiaelectiondata"
languages:
  - name: 'English'
    key: 'en'
  - name: 'French'
    key: 'fr'
  - name: 'Arabic'
    key: 'ar'
