auto: true
server: true
permalink: /:categories/:title
github: "https://github.com/mbaldassaro/tunisiaelectiondata"
baseurl: /tunisiaelectiondata
languages:
  - name: 'English'
    key: 'en'
  - name: 'French'
    key: 'fr'
  - name: 'Arabic'
    key: 'ar'
